--Insert statements for the various colleges
INSERT INTO colleges (name) VALUES('College of Agriculture and Natural Resources');
INSERT INTO colleges (name) VALUES('College of Art and Built Environment');
INSERT INTO colleges (name) VALUES('College of Engineering');
INSERT INTO colleges (name) VALUES('College of Health Sciences');
INSERT INTO colleges (name) VALUES('College of Humanities and Social Sciences');
INSERT INTO colleges (name) VALUES('College of Science');

--
INSERT INTO programmes (name, college_id) VALUES ('BSc. Agriculture', 1);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Agricultural Biotechnology', 1);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Agribusiness Management', 1);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Landscape Design and Management', 1);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Natural Resource Management', 1);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Forest Resources Technology', 1);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Packaging Technology', 1);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Aquaculture and Water Resource Management', 1);
--
INSERT INTO programmes (name, college_id, duration) VALUES ('BSc. Architecture', 2, 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Construction Technology and Management', 2);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Quantity Surveying and Construction Economics', 2);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Development Planning', 2);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Human Settlement Planning', 2);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Land Economy', 2);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Real Estate', 2);
INSERT INTO programmes (name, college_id) VALUES ('BA. Communication Design', 2);
INSERT INTO programmes (name, college_id) VALUES ('BA. Integrated Rural Art and Industry', 2);
INSERT INTO programmes (name, college_id) VALUES ('BA. Publishing Studies', 2);
INSERT INTO programmes (name, college_id) VALUES ('BFA. Ceramics', 2);
INSERT INTO programmes (name, college_id) VALUES ('BA. Metal Product Design Technology', 2);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Textile Design and Technology', 2);
INSERT INTO programmes (name, college_id) VALUES ('BFA. Fine Art and Curatorial Practice', 2);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Fashion Design', 2);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Ceramics Technology', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed. Junior High School Education', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed Chemistry', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed. Biology', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed. Mathematics', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed. Physics', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed. STEM (Aviation and Aerospace)', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed. STEM (Manufacturing)', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed. STEM (Robotics)', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed. STEM (Biomedical Science)', 2);
INSERT INTO programmes (name, college_id) VALUES ('B.Ed. Art and Design Technology', 2);
--
INSERT INTO programmes (name, college_id) VALUES ('BSc. Civil Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Geological Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Geomatic Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Petroleum Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Biomedical Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Computer Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Electrical/Electronic Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Telecommunications Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Agricultural Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Petrochemical Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Chemical Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Metallurgical Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Materials Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Marine Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Industrial Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Automobile Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Mechanical Engineering', 3);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Aerospace Engineering', 3);
--
INSERT INTO programmes (name, college_id) VALUES ('BSc. Physiotherapy and Sports Science', 4);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Medical Imaging', 4);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Medical Laboratory Science', 4);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Nursing', 4);
INSERT INTO programmes (name, college_id, duration) VALUES ('Nursing (practicing nurses only)', 4, 2);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Midwifery', 4);
INSERT INTO programmes (name, college_id, duration) VALUES ('BSc. Midwifery (practicing midwives only)', 4, 2);
INSERT INTO programmes (name, college_id) VALUES ('Bachelor of Herbal Medicine', 4);
INSERT INTO programmes (name, college_id, duration) VALUES ('Doctor of Pharmacy (Pharm D)', 4, 6);
INSERT INTO programmes (name, college_id, duration) VALUES ('Doctor of Pharmacy (Pharm D), (practicing pharmacists only)', 4, 2);
INSERT INTO programmes (name, college_id, duration) VALUES ('Human Biology (Medicine)', 4, 6);
INSERT INTO programmes (name, college_id, duration) VALUES ('Bachelor of Dental Surgery', 4, 6);
INSERT INTO programmes (name, college_id, duration) VALUES ('Doctor of Veterinary Medicine', 4, 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Disability and Rehabilitation Studies', 4);
--
INSERT INTO programmes (name, college_id) VALUES ('Bachelor of Laws (LLB)', 5);
INSERT INTO programmes (name, college_id, duration) VALUES ('LLB (Degree Holders Only) (Fee-Paying)', 5, 2);
INSERT INTO programmes (name, college_id) VALUES ('BA. Economics', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. English', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. Geography and Rural Development', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. History', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. Political Studies', 5);
INSERT INTO programmes (name, college_id) VALUES ('Bachelor of Public Administration', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. Akan Language and Culture', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. French and Francophone Studies', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. Linguistics', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. Media and Communication Studies', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. Religion and Human Development', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. Sociology', 5);
INSERT INTO programmes (name, college_id) VALUES ('BA. Social Work', 5);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Business Administration (Human Resource Management Management)', 5);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Business Administration (Marketing/International Business)', 5);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Business Administration (Accounting / Banking and Finance)', 5);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Business Administration (Logistics and Supply Chain Management/Business Information Technology)', 5);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Hospitality and Tourism Management', 5);
--
INSERT INTO programmes (name, college_id) VALUES ('BSc. Biochemistry', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Food Science and Technology', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Dietetics', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Human Nutrition', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Biological Science', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Environmental Science', 6);
INSERT INTO programmes (name, college_id) VALUES ('Doctor of Optometry', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Chemistry', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Mathematics', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Physics', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Computer Science', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Statistics', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Actuarial Science', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Meteorology and Climate Science', 6);
INSERT INTO programmes (name, college_id) VALUES ('BSc. Information Technology', 6);
